import { evidence } from './evidence.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(value,digits=4)=>Number(value).toLocaleString('en-SG',{maximumFractionDigits:digits});
export function getRecords(){return evidence.records.map(r=>({...r,damage:r.prediction,prediction:'Damage estimate',title:`Fatigue damage · ${number(r.prediction)}`,provenance:'Calculated from official SHM test records'}));}
export function statisticsText(r){return [`Estimated fatigue damage: ${number(r.damage)} on the supplied reference scale.`,`Calculated from ${number(r.readings,0)} stress readings. This is not a percentage damaged, failure probability or remaining-life estimate.`];}
export function recommendation(){return 'Review large stress changes against operating records and compare the estimate with asset history. Ask the responsible engineer to interpret it against applicable maintenance criteria; this result alone does not establish whether the structure is safe.';}
function stressChart(r){
 const w=720,h=190,left=65,right=20,top=15,bottom=32;
 const lo=Math.min(...r.overview.map(p=>p.minimum)),hi=Math.max(...r.overview.map(p=>p.maximum));
 const x=p=>left+p.sample/Math.max(1,r.readings-1)*(w-left-right);
 const y=v=>top+(hi-v)/Math.max(1e-12,hi-lo)*(h-top-bottom);
 const points=key=>r.overview.map(p=>`${x(p).toFixed(2)},${y(p[key]).toFixed(2)}`).join(' ');
 return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Stress range across ${escape(r.file)}"><title>Stress envelope for ${escape(r.file)}</title><line x1="${left}" y1="${h-bottom}" x2="${w-right}" y2="${h-bottom}" stroke="var(--nx-line)"/><polyline points="${points('maximum')}" fill="none" stroke="var(--nx-accent)" stroke-width="1.4"/><polyline points="${points('minimum')}" fill="none" stroke="var(--nx-muted)" stroke-width="1.2"/><g fill="var(--nx-muted)" font-size="12"><text x="2" y="22">${number(hi,2)}</text><text x="2" y="${h-bottom}">${number(lo,2)}</text><text x="${left}" y="${h-8}">Start</text><text x="${w-right}" y="${h-8}" text-anchor="end">End of record</text></g></svg>`;
}
function cycleChart(r){const max=Math.max(1,...r.cycles.map(c=>c.count));return `<div class="nx-tablewrap"><table class="nx-results"><caption>Stress-cycle size and frequency</caption><thead><tr><th>Stress range</th><th>Frequency</th><th>Cycles</th></tr></thead><tbody>${r.cycles.map(c=>`<tr><td>${number(c.low,2)}–${number(c.high,2)}</td><td style="min-width:85px"><div class="nx-track"><div style="width:${100*c.count/max}%"></div></div></td><td>${number(c.count,1)}</td></tr>`).join('')}</tbody></table></div>`;}
export function renderStatistics(r){return `<link rel="stylesheet" href="./components/shm/view.css"><div class="shm-insight"><div class="shm-damage-card"><span>Estimated fatigue damage</span><strong>${number(r.damage)}</strong><p>Reference index · not a percentage</p></div><p class="shm-intro">Repeated loading can contribute to fatigue. This estimate summarises the loading in this record; higher values mean more estimated damage on the same reference scale.</p><div class="shm-facts"><div><strong>${number(r.readings,0)}</strong><span>Stress readings</span></div><div><strong>${number(r.features.rf_cycle_count,1)}</strong><span>Loading cycles</span></div></div><h3>How did the loading change?</h3><p>Teal shows the highest stress and grey the lowest in each section. A wider gap means more variation—not automatically a fault.</p>${stressChart(r)}<p class="nx-small">Source stress units; the chart summarises the signal, not elapsed time.</p><details><summary>Repeated loading</summary><p>Rainflow counting groups stress changes into cycles. Larger ranges mean bigger stress swings.</p>${cycleChart(r)}</details><details><summary>Technical measurements</summary><div class="nx-tablewrap"><table class="nx-results"><tbody>${Object.entries(r.features).map(([key,value])=>`<tr><th>${escape(key)}</th><td>${number(value,6)}</td></tr>`).join('')}</tbody></table></div><p class="nx-small">Model: ${escape(r.model_version)}</p></details>${r.warnings.map(w=>`<p class="nx-notice">${escape(w)}</p>`).join('')}</div>`;}
