// Component-owned UX. Keep prediction and feature-extraction logic in the existing Python pipeline.
export const config = {
  "name": "Rail corrugation",
  "short": "Rail",
  "icon": "route",
  "status": "Pipeline implemented",
  "input": "One or more recording CSVs",
  "format": "10,000 rows × 129 columns per recording",
  "output": "Normal / Side I / Side II",
  "title": "Possible Side I corrugation",
  "finding": "The model identifies a pattern associated with Side I corrugation in this recording.",
  "scope": "Recording-level finding. Exact track location is not supplied.",
  "next": "Review the recording and corroborating inspection evidence.",
  "why": "Side I and Side II are the dataset’s condition labels. They do not identify a geographic track location or a particular car.",
  "evidence": "In five-fold validation, Side I recall was 78.6% and precision was 52.4%. A Side I prediction warrants checking: false positives occurred in validation.",
  "file": "rail-example-01.csv"
};
export function renderInterpretation(state) { return `<p class="nx-small">Illustrative recording · Adjusted class scores</p>${(state.normal?[['Normal',.81],['Side I',.12],['Side II',.07]]:[['Normal',.21],['Side I',.68],['Side II',.11]]).map(([name,value])=>`<div class="nx-score"><span>${name}</span><div class="nx-track"><div style="width:${value*100}%"></div></div><strong>${value.toFixed(2)}</strong></div>`).join('')}<p>${state.normal?'Normal has the highest adjusted score (0.81).':'Side I has the highest adjusted score (0.68), ahead of Normal (0.21).'} These are example model scores, not calibrated probabilities or measured fault severity.</p><div class="nx-notice">Actual validation: 11 of 14 Side I recordings were detected (78.6% recall). Of 21 Side I predictions, 11 were correct (52.4% precision).</div><p class="nx-small">Validation describes overall model performance, not proof of this individual finding. Signal statistics and baseline comparisons will be calculated from the uploaded recording.</p>`; }
export function renderMethod() { return `<div class="nx-sectionhead"><h2>Random forest with class balancing</h2><span class="nx-pill quiet">Implemented</span></div><p>272 labelled recordings: 234 Normal, 14 Side I, 24 Side II.</p><ol class="nx-method"><li><strong>Prepare each recording</strong><p>Validate 10,000 rows × 129 columns. Derive statistical signal features from the recording.</p></li><li><strong>Select features within each training fold</strong><p>Median imputation, removal of constant features, and the 30 highest-ranked features using ANOVA F scores.</p></li><li><strong>Balance and fit the model</strong><p>SMOTE raises each minority class to 48 training examples (k = 2). Fit 500 trees, square-root feature sampling and a minimum split size of 4.</p></li><li><strong>Adjust and compare class scores</strong><p>Apply a 1.5 multiplier to Side I scores before the final decision. Adjusted scores are not calibrated probabilities.</p></li><li><strong>Test on held-out folds</strong><p>Five-fold validation (seed 42), with preprocessing and resampling fitted only on the training fold. Repeat across seeds 7, 19, 42, 73 and 101 to check stability.</p></li></ol><div class="nx-evidence"><div class="nx-metric"><strong>82.3%</strong><span>Fixed five-fold macro F1</span></div><div class="nx-metric"><strong>82.3%</strong><span>Mean macro F1 across five seeds</span></div></div><div class="nx-tablewrap"><table class="nx-results"><caption>Held-out predictions · Actual class → predicted class</caption><thead><tr><th>Actual</th><th>Normal</th><th>Side I</th><th>Side II</th></tr></thead><tbody><tr><th>Normal</th><td>225</td><td>7</td><td>2</td></tr><tr><th>Side I</th><td>3</td><td>11</td><td>0</td></tr><tr><th>Side II</th><td>1</td><td>3</td><td>20</td></tr></tbody></table></div><details><summary class="cursor-interaction">Why this method &amp; what we tested</summary><p>The research compared alternative classifiers and feature sets. A further 19 Random Forest variants did not improve the frozen baseline; the best new variant reached macro F1 0.8211 versus baseline 0.8234.</p><p>The 68 competition test recordings are unlabelled. Their predictions are outputs, not evidence of test-set accuracy. Side I false positives and missed faults remain important review cases.</p></details>`; }
