import { evidence } from './evidence.js';
export function getRecords(){return evidence.records.map(r=>({...r,title:r.prediction==='Normal'?'Normal prediction':`Possible ${r.prediction} corrugation`,provenance:'Calculated reference recording · Unlabelled test data'}));}
const number=n=>Number.isFinite(n)?n.toFixed(4):'Not available';
export function statisticsText(r){
 const s=r.stats, a=s.side1_vibration_rms_mean,b=s.side2_vibration_rms_mean;
 const stronger=a>=b?'Side I':'Side II',lo=Math.min(a,b),hi=Math.max(a,b);
 const difference=lo>0?`${stronger} vibration is ${((hi/lo-1)*100).toFixed(1)}% higher than the other side.`:'A relative comparison cannot be calculated because one side has zero RMS.';
 
 return [difference,r.prediction==='Normal'?'No corrugation pattern was detected.':`The model flagged possible ${r.prediction} corrugation. Check this against inspection findings.`];
}
export function recommendation(r){return r.prediction==='Normal'?'Record the Normal result and compare with prior recordings from the same asset and operating conditions. If vibration complaints or inspection findings disagree, retain this recording for engineering review.':'Review the indicated side’s vibration and shock channels, compare with prior recordings under similar operating conditions, and corroborate against the applicable rail inspection procedure. Confirm asset/location metadata before assigning work; this recording supplies no track location.';}
export function renderStatistics(r){const s=r.stats;return `<p class="nx-small">${r.rows.toLocaleString()} readings · ${r.channels} sensor channels · Units as supplied in the dataset</p><div class="nx-tablewrap"><table class="nx-results"><caption>Calculated signal statistics</caption><thead><tr><th>Measurement</th><th>Side I</th><th>Side II</th></tr></thead><tbody>${[['Mean channel vibration RMS','vibration_rms_mean'],['Mean channel shock RMS','shock_rms_mean'],['Mean channel vibration peak','vibration_peak_mean']].map(([label,k])=>`<tr><th>${label}</th><td>${number(s['side1_'+k])}</td><td>${number(s['side2_'+k])}</td></tr>`).join('')}</tbody></table></div><p class="nx-small">RMS summarises signal strength. Peak summarises the largest readings across channels.</p>${statisticsText(r).map(t=>`<p class="nx-spaced">${t}</p>`).join('')}<details><summary>Calculated model scores</summary>${Object.entries(r.scores).map(([label,value])=>`<div class="nx-score"><span>${label}</span><div class="nx-track"><div style="width:${value*100}%"></div></div><strong>${value.toFixed(3)}</strong></div>`).join('')}<p>Model scores compare the classes; they are not fault probabilities.</p></details>`;}
