import { evidence } from './evidence.js';
import {liveResult} from '../../cloud-client.js';
export function getRecords(){return (liveResult('door')?.records||evidence.records).map(r=>({...r,title:r.prediction==='Normal'?'Normal movement':'Possible abnormal resistance',provenance:'Calculated recording · Hidden labels unavailable'}));}
const metrics=[['Mean absolute current','mean_abs_current_A'],['Peak absolute current','peak_abs_current_A'],['Current standard deviation','current_std_A'],['Early-third current','early_current_A'],['Middle-third current','middle_current_A'],['Late-third current','late_current_A']];
const num=n=>n.toFixed(3);
// Dataset timestamps are local/unspecified time, not UTC. Preserve them in exports.
export function formatTimestamp(value){
 const [year,month,day,hour,minute,second,millisecond]=value.split('-').map(Number);
 const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
 const pad=n=>String(n).padStart(2,'0');
 return `${pad(day)} ${months[month-1]} ${year} · ${pad(hour)}:${pad(minute)}:${pad(second)}.${String(millisecond).padStart(3,'0')}`;
}
export function statisticsText(r){return [`${r.stats.opening_from_position?'Opening':'Closing'} movement lasting ${r.duration.toFixed(2)} s, with ${r.rows} readings and net position change ${r.positionChange} native units.`,...metrics.map(([label,k])=>`${label}: ${num(r.stats[k])} A; training-normal range for the same direction: ${num(r.ranges[k][0])}–${num(r.ranges[k][1])} A.`),`Abnormal model score ${r.abnormalScore.toFixed(4)} against threshold 0.5 gives ${r.prediction}. Scores are not calibrated fault probabilities. Current comparisons are descriptive context, not independent fault thresholds.`];}
export function recommendation(r){return r.prediction==='Normal'?'Record the Normal result and compare the movement with previous recordings from the same door. Investigate unusual travel, timing or reported symptoms even when the current-pattern model predicts Normal.':'Inspect the flagged movement and compare its early, middle and late current with normal movements in the same direction. Follow the applicable door inspection procedure to investigate resistance; these readings do not identify a specific failed part.';}
export function renderStatistics(r){return `<p class="nx-small"><strong>Start</strong> &nbsp; ${formatTimestamp(r.start)}<br><strong>End</strong> &nbsp; ${formatTimestamp(r.end)}</p><p>${statisticsText(r)[0]}</p><div class="nx-tablewrap"><table class="nx-results"><caption>Calculated current measurements · ${r.stats.opening_from_position?'Opening':'Closing'}</caption><thead><tr><th>Measurement</th><th>This movement</th><th>Training Normal range, same direction</th></tr></thead><tbody>${metrics.map(([label,k])=>`<tr><th>${label}</th><td>${num(r.stats[k])} A</td><td>${num(r.ranges[k][0])}–${num(r.ranges[k][1])} A</td></tr>`).join('')}</tbody></table></div><p class="nx-spaced">${statisticsText(r).at(-1)}</p><details><summary>Calculated model scores</summary>${[['Normal',1-r.abnormalScore],['Abnormal resistance',r.abnormalScore]].map(([label,value])=>`<div class="nx-score"><span>${label}</span><div class="nx-track"><div style="width:${value*100}%"></div></div><strong>${value.toFixed(3)}</strong></div>`).join('')}</details>`;}
