import * as rail from './components/rail/index.js';
import * as door from './components/door/index.js';
import * as acv from './components/acv/index.js';
import * as shm from './components/shm/index.js';
const components={rail,door,acv,shm};
const modules=Object.fromEntries(Object.entries(components).map(([key,value])=>[key,value.config]));
const root=document.getElementById('nx-ops'),content=root.querySelector('#nx-content');
let state={page:'review',module:'rail',normal:false,reviewed:{},notes:{},feedback:{},exportOpen:false,message:''};

const design={density:'Comfortable',corners:14,guidance:true};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=()=>state.module+(state.normal?'-normal':'');
function save() {} // In-memory prototype; backend persistence is a separate integration task.
const action=(label,attrs='',primary=false)=>`<button type="button" class="cursor-interaction nx-action ${primary?'nx-primary':''}" ${attrs}>${label}</button>`;
function cards(){return `<div class="nx-components" aria-label="Components">${Object.entries(modules).map(([k,m])=>`<button type="button" class="cursor-interaction nx-component" data-module="${k}" aria-pressed="${state.module===k}"><strong>${m.name}</strong><span>${m.status}</span></button>`).join('')}</div>`;}
function title(kicker,heading,sub){return `<div class="nx-title nx-centered"><div><div class="nx-kicker">${kicker}</div><h1>${heading}</h1><p>${sub}</p></div></div>`;}
function stats(){return components[state.module].renderInterpretation(state);}
function exports(){return `<section class="nx-detail nx-export" aria-label="Download findings"><div class="nx-sectionhead"><h2>Download findings</h2>${action('Close','data-close-export')}</div><div class="nx-export-grid"><div><h3>Competition predictions</h3><p>Required prediction columns only; review notes stay out of the submission file.</p>${action(state.module==='rail'?'Download sample CSV':'Awaiting validated pipeline',state.module==='rail'?'data-download="csv"':'disabled',true)}<p class="nx-small">${state.module==='rail'?'Preview: demo_rail_predictions.csv · 2 illustrative rows':'Competition CSV will unlock after pipeline integration and output checks.'}</p></div><div><h3>Operator findings report</h3><p>All sample findings for this component, interpretation, review status and notes.</p>${action('Download sample report','data-download="report"')}<p class="nx-small">Readable text report · Includes a sample-data watermark</p></div></div><p class="nx-small">Final submission: export each component’s required CSV, then package the completed files in predictions.zip. This preview is not a competition submission. Sample downloads work locally; production exports require backend integration.</p>${state.exportPreview?`<label for="nx-export-content" class="nx-small">${escape(state.exportPreview.filename)}</label><textarea id="nx-export-content" readonly aria-label="Export content preview">${escape(state.exportPreview.text)}</textarea>`:''}</section>`;}
function review(){const m=modules[state.module],id=key(),done=state.reviewed[id],normal=state.normal;return title('Operations / Review','Know what needs a closer look.','Understand the finding. Record your judgment. Take the results with you.')+`<div class="nx-toolbar">${action('New analysis','data-go="analyze"',true)}${action('Download findings','data-export')}<span class="nx-small">${m.name} · Sample batch</span></div>`+cards()+(state.exportOpen?exports():'')+`<div class="nx-sectionhead"><h2>${m.name}</h2><span class="nx-count">${state.module==='rail'?'2 sample recordings':'1 sample recording'}</span></div><div class="nx-workspace"><section class="nx-list" aria-label="Sample recordings"><button class="cursor-interaction nx-record" data-record="finding" aria-pressed="${!normal}"><span class="nx-pill ${state.reviewed[state.module]?'quiet':''}">${state.reviewed[state.module]?'Reviewed':'Needs review'}</span><strong>${m.title}</strong><p>${m.file}</p></button>${state.module==='rail'?`<button class="cursor-interaction nx-record" data-record="normal" aria-pressed="${normal}"><span class="nx-pill quiet">${state.reviewed['rail-normal']?'Reviewed':'Normal prediction'}</span><strong>Normal classification</strong><p>rail-example-02.csv</p></button>`:''}<p class="nx-small">Sample findings · No live monitoring</p></section><article class="nx-detail" aria-label="Selected finding"><span class="nx-pill ${done||normal?'quiet':''}">${done?'Reviewed':normal?'Normal prediction':'Review suggested'}</span><h2>${normal?'No corrugation pattern detected':m.title}</h2><p>${normal?'The model classified this example recording as Normal.':m.finding}</p><div class="nx-step"><h3>Suggested next step</h3><p>${normal?'Include this result in the routine review of the recording.':m.next}</p></div><p class="nx-small">${m.scope}</p><details ${design.guidance?'open':''}><summary class="cursor-interaction">Interpret this finding · Numbers &amp; context</summary>${stats()}<p>${m.why}</p></details><hr class="nx-divider"><label for="nx-note" class="nx-small">Review note</label><textarea id="nx-note" placeholder="What did you observe? Include confirmed findings or corrections…">${escape(state.notes[id]||'')}</textarea><div class="nx-inline">${action(done?'Reopen review':'Mark as reviewed','data-review',!done)}${action('Use note for AI improvement','data-feedback')}</div>${state.feedback[id]?`<div class="nx-notice"><strong>Feedback saved in this preview</strong><p>Next: an engineer verifies the observation before it enters model development.</p></div>`:''}<p class="nx-toast" role="status">${escape(state.message)}</p></article></div>`;}
function analyze(){const m=modules[state.module];return title('Analysis / New','Start with a recording.','One shared workflow for every component.')+`<div class="nx-flow"><b>01 Choose component</b><span>02 Validate input</span><span>03 Review &amp; download</span></div><section class="nx-detail"><label for="nx-module">Component</label><select id="nx-module">${Object.entries(modules).map(([k,v])=>`<option value="${k}" ${state.module===k?'selected':''}>${v.name}</option>`).join('')}</select><h2>${m.input}</h2><p>${m.format}</p><div class="nx-empty"><h3>Recording upload belongs here</h3><p>Upload and validation will be connected in the working app.</p></div><div class="nx-sectionhead"><div><h3>Result</h3><p>${m.output}</p></div>${action('Explore sample result','data-go="review"',true)}</div><div class="nx-notice">${state.module==='rail'?'The Rail pipeline is implemented. This design preview does not run the model.':'This component’s pipeline is awaiting team integration.'}</div><p class="nx-small">Invalid inputs will be identified before analysis. Validated predictions will be available as a competition CSV and an operator report.</p></section>`;}
function method(){return title('Understand / Model evidence','How we reached the result.','Explore the model, experiment and tests for each component.')+cards()+`<section class="nx-detail">${components[state.module].renderMethod()}</section>`;}
function learning(){const entries=Object.values(state.feedback);return title('Improve / Human feedback','Turn experience into better models.','A proposed AI-assisted improvement cycle for all four components.')+`<section class="nx-detail"><span class="nx-pill">Concept · AI backend not connected</span><ol class="nx-method"><li><strong>Collect the review</strong><p>Keep the note, recording ID, component and prediction together.</p></li><li><strong>Verify the observation</strong><p>An engineer confirms the outcome or corrected label. Free-text notes do not become ground truth automatically.</p></li><li><strong>Propose a change with AI</strong><p>AI can group recurring errors and draft feature, model or code changes in a separate development branch.</p></li><li><strong>Run tests and compare</strong><p>Retrain if needed. Compare the candidate with the current baseline on a fixed evaluation set, check per-class performance and run input/output regression tests.</p></li><li><strong>Approve and release a version</strong><p>Publish a reviewed model/code version with its evaluation results and a rollback path.</p></li></ol><hr class="nx-divider"><h2>Feedback collected in this preview</h2>${entries.length?entries.map(e=>`<div class="nx-step"><h3>${escape(modules[e.module].name)} · ${escape(e.file)}</h3><p>${escape(e.note)}</p><span class="nx-pill">Awaiting verification</span></div>`).join(''):'<p>No feedback yet. Add a review note, then choose “Use note for AI improvement”.</p>'}</section>`;}
function reportText(){const m=modules[state.module],keys=state.module==='rail'?['rail','rail-normal']:[state.module];return ['NEBULAX — SAMPLE FINDINGS REPORT','DESIGN PREVIEW ONLY — NOT FOR OPERATIONAL USE OR COMPETITION SUBMISSION','Component: '+m.name,'',...keys.flatMap(id=>['Recording: '+(id==='rail-normal'?'rail-example-02.csv':m.file),'Finding: '+(id==='rail-normal'?'Normal classification':m.title),'Interpretation: '+(id==='rail-normal'?'Illustrative adjusted scores: Normal 0.81, Side I 0.12, Side II 0.07.':state.module==='rail'?'Illustrative adjusted scores: Normal 0.21, Side I 0.68, Side II 0.11.':state.module==='door'?'Illustrative interval: 12.4–15.8 s; duration 3.4 s.':state.module==='acv'?'Illustrative car ranking: 3,6,1,8,2,5,4,7.':'Numerical estimate awaiting integration.'),m.why,'Review status: '+(state.reviewed[id]?'Reviewed':'Not reviewed'),'Review note: '+(state.notes[id]||'None'),'']),state.module==='rail'?'Actual validation context: macro F1 0.8234; Side I recall 11/14 (78.6%); precision 11/21 (52.4%). This does not validate the illustrative findings.':'Model and measured validation results awaiting team integration.'].join('\n');}
function download(kind){
 const text=kind==='csv'?'file_id,prediction\nrail-example-01.csv,Side I\nrail-example-02.csv,Normal\n':reportText();
 const filename=kind==='csv'?'demo_rail_predictions.csv':`demo_${state.module}_findings.txt`;
 const url=URL.createObjectURL(new Blob([text],{type:kind==='csv'?'text/csv;charset=utf-8':'text/plain;charset=utf-8'}));
 const link=document.createElement('a');link.href=url;link.download=filename;root.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
 state.exportPreview={filename,text};state.message='Sample download prepared: '+filename;
}
function render(){root.style.setProperty('--nx-radius',design.corners+'px');root.classList.toggle('nx-compact',design.density==='Compact');root.querySelectorAll('[data-page]').forEach(b=>{if(b.dataset.page===state.page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});content.innerHTML=state.page==='review'?review():state.page==='analyze'?analyze():state.page==='learning'?learning():method();}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.message='';if(b.dataset.page||b.dataset.go)state.page=b.dataset.page||b.dataset.go;else if(b.dataset.module){state.module=b.dataset.module;state.normal=false;state.exportPreview=null;}else if(b.dataset.record)state.normal=b.dataset.record==='normal';else if(b.hasAttribute('data-review')){state.reviewed[key()]=!state.reviewed[key()];state.message=state.reviewed[key()]?'Review recorded in this preview.':'Review reopened.';}else if(b.hasAttribute('data-feedback')){const note=(state.notes[key()]||'').trim();if(!note)state.message='Add a review note before collecting improvement feedback.';else{state.feedback[key()]={module:state.module,file:state.normal?'rail-example-02.csv':modules[state.module].file,note};state.message='Added to AI improvement → Awaiting verification. No model or code was changed.';}}else if(b.hasAttribute('data-export'))state.exportOpen=!state.exportOpen;else if(b.hasAttribute('data-close-export'))state.exportOpen=false;else if(b.dataset.download)download(b.dataset.download);else return;render();save();});
root.addEventListener('change',e=>{if(e.target.id==='nx-module'){state.module=e.target.value;state.normal=false;render();save();}});root.addEventListener('input',e=>{if(e.target.id==='nx-note')state.notes[key()]=e.target.value;});
render();
